import { Shield, Zap, Radio, Copy, Pause, Keyboard, Gamepad2 } from 'lucide-react';
import type { Simulation } from '../game/simulation';

type State = Simulation['state'];
export function Hud({ state, device, onPause, best, practice }: { state: State; device: 'keyboard' | 'gamepad'; onPause: () => void; best: number; practice: boolean }) {
  const boss = state.boss;
  const objective = state.status === 'extraction' ? 'Reach the open north exit' : boss ? boss.charge >= 3 ? 'Cross the discharge pad in recovery' : `Collect relay ${Math.min(3, boss.charge + 1)} of 3` : `Collect ${state.quota} energy cores`;
  return <div className="hud" aria-label="Gameplay status">
    <section className="hud-objective panel"><div className="hud-kicker"><span>{practice ? 'PRACTICE' : 'DISTRICT 01'}</span><span>{boss ? 'WARDEN' : `WAVE ${state.wave} / 3`}</span></div><h2>NEON SPIRE</h2><div className="objective-line"><span>{objective}</span><strong>{boss ? `${3 - boss.nodes} / 3` : `${state.coresCollected} / ${state.quota}`}</strong></div><div className="meter"><i style={{ width: `${boss ? (3 - boss.nodes) / 3 * 100 : state.coresCollected / state.quota * 100}%` }} /></div>{boss ? <div className={`boss-phase ${boss.phase}`}>{boss.phase === 'recovery' ? 'DISCHARGE WINDOW OPEN' : boss.phase === 'warning' ? 'LASER FAN · WARNING' : boss.phase === 'attack' ? 'LASER FAN · ACTIVE' : 'COLLECT RELAYS'}<span>{Math.ceil(boss.phaseTime)}s</span></div> : null}</section>
    <section className="hud-score panel"><div><span className="hud-label">SCORE</span><strong>{state.score.toLocaleString('en-US')}</strong></div><div className="local-best"><span className="hud-label">LOCAL BEST</span><span>{best.toLocaleString('en-US')}</span></div>{state.combo > 1 ? <div className="combo"><span className="hud-label">COMBO</span><strong>×{state.combo}</strong><div className="meter"><i style={{ width: `${state.comboTimer / 5 * 100}%` }} /></div></div> : null}<button className="icon-button" onClick={onPause} aria-label="Pause game"><Pause size={19} /></button></section>
    <section className="hud-resources panel"><div className="resource-line"><Shield size={19} /><div><span className="hud-label">SNAKE INTEGRITY</span><div className="integrity" aria-label={`${state.player.integrity} of ${state.player.maxIntegrity} integrity`}>{Array.from({ length: state.player.maxIntegrity }, (_, i) => <i key={i} className={i < state.player.integrity ? 'filled' : ''} />)}</div></div><span className="length-label">{state.player.length}<small>SEGMENTS</small></span></div><div className="resource-line"><Zap size={20} /><div><div className="boost-label"><span className="hud-label">BOOST ENERGY</span><span>{Math.round(state.player.boost)}%</span></div><div className="meter"><i style={{ width: `${state.player.boost}%` }} /></div></div></div></section>
    <section className="hud-tactics panel"><span className="hud-label">TACTICAL SYSTEMS <span>{device === 'keyboard' ? 'E' : 'Y'} TO SWITCH</span></span><div className="tactic-slots">{[{ icon: Radio, title: 'EMP PULSE' }, { icon: Copy, title: 'DECOY' }].map(({ icon: Icon, title }, i) => <div key={title} className={`tactic ${state.selectedSlot === i ? 'selected' : ''} ${state.slots[i] ? 'ready' : ''}`}><Icon size={23} /><div><span>{title}</span><small>{state.slots[i] ? 'READY' : 'EMPTY'}</small></div>{state.selectedSlot === i ? <kbd>{device === 'keyboard' ? 'SPACE' : 'X'}</kbd> : null}</div>)}</div></section>
    <div className="input-hints">{device === 'keyboard' ? <Keyboard size={16} /> : <Gamepad2 size={17} />}<span>Steer <b>{device === 'keyboard' ? 'WASD / ARROWS' : 'LEFT STICK / D-PAD'}</b></span><span>Boost <b>{device === 'keyboard' ? 'SHIFT' : 'RT'}</b></span><span>Pause <b>{device === 'keyboard' ? 'ESC' : 'MENU'}</b></span></div>
    <div className="active-buffs">{Object.entries(state.buffs).filter(([, ttl]) => ttl > 0).map(([name, ttl]) => <span key={name}>{name === 'surge' ? 'SCORE SURGE' : name.toUpperCase()} <b>{Math.ceil(ttl)}s</b></span>)}</div>
  </div>;
}
