import { Shield, Zap, Radio, Copy, Pause, Keyboard, Gamepad2 } from 'lucide-react';
import type { Simulation } from '../game/simulation';
import { PICKUPS } from '../game/content';

type State = Simulation['state'];
export function Hud({ state, device, onPause, best, practice }: { state: State; device: 'keyboard' | 'gamepad'; onPause: () => void; best: number; practice: boolean }) {
  const boss = state.boss;
  const use = device === 'keyboard' ? 'SPACE' : 'X';
  const combat = [...state.events].reverse().find(event => ['damage', 'shield-hit'].includes(event.kind) && state.time - event.time < 2);
  const buffEffects = { overdrive: 'Half boost drain', shield: 'Absorbs one attack', surge: 'Core / rival points ×2', magnet: 'Nearby core attraction' };
  const activeBuffs = (Object.keys(state.buffs) as (keyof typeof state.buffs)[]).filter(kind => state.buffs[kind] > 0);
  const tacticalHint = state.slots[state.selectedSlot] ? state.selectedSlot === 0 ? `${use} · Disable nearby drones / emitters for 3s` : `${use} · Deploy a 4s holographic lure`
    : state.selectedSlot === 0 ? state.boss ? 'No new EMP pickups during Warden. Relays do not require tactics.' : state.mode === 'campaign' && state.wave === 1 ? 'EMP charges arrive in Wave 2. Squares here activate automatically.' : 'Collect a cyan ◎ square to load one EMP charge.'
      : state.mode === 'campaign' ? 'Decoy charges are available in Practice.' : 'Collect a purple ⋈ square to load one Decoy charge.';
  const objective = state.status === 'extraction' ? 'Reach the open north exit' : boss ? boss.charge >= 3 ? 'Cross the discharge pad in recovery' : `Collect relay ${Math.min(3, boss.charge + 1)} of 3` : `Collect ${state.quota} energy cores`;
  return <div className="hud" aria-label="Gameplay status">
    <section className="hud-objective panel"><div className="hud-kicker"><span>{practice ? 'PRACTICE' : 'DISTRICT 01'}</span><span>{boss ? 'WARDEN' : `WAVE ${state.wave} / 3`}</span></div><h2>NEON SPIRE</h2><div className="objective-line"><span>{objective}</span><strong>{boss ? `${3 - boss.nodes} / 3` : `${state.coresCollected} / ${state.quota}`}</strong></div><div className="meter"><i style={{ width: `${boss ? (3 - boss.nodes) / 3 * 100 : state.coresCollected / state.quota * 100}%` }} /></div>{boss ? <div className={`boss-phase ${boss.phase}`}>{boss.phase === 'recovery' ? 'DISCHARGE WINDOW OPEN' : boss.phase === 'warning' ? 'LASER FAN · WARNING' : boss.phase === 'attack' ? 'LASER FAN · ACTIVE' : 'COLLECT RELAYS'}<span>{Math.ceil(boss.phaseTime)}s</span></div> : null}</section>
    <section className="hud-score panel"><div><span className="hud-label">SCORE</span><strong>{state.score.toLocaleString('en-US')}</strong></div><div className="local-best"><span className="hud-label">LOCAL BEST</span><span>{best.toLocaleString('en-US')}</span></div>{state.combo > 1 ? <div className="combo"><span className="hud-label">COMBO</span><strong>×{state.combo}</strong><div className="meter"><i style={{ width: `${state.comboTimer / 5 * 100}%` }} /></div></div> : null}<button className="icon-button" onClick={onPause} aria-label="Pause game"><Pause size={19} /></button></section>
    <section className={`hud-resources panel ${combat?.kind === 'damage' ? 'recent-damage' : ''}`}><div className="resource-line"><Shield size={19} /><div><span className="hud-label">SNAKE INTEGRITY</span><div className="integrity" aria-label={`${state.player.integrity} of ${state.player.maxIntegrity} integrity`}>{Array.from({ length: state.player.maxIntegrity }, (_, i) => <i key={i} className={i < state.player.integrity ? 'filled' : ''} />)}</div></div><span className="length-label">{state.player.length}<small>SEGMENTS</small></span></div><div className="resource-line"><Zap size={20} /><div><div className="boost-label"><span className="hud-label">BOOST ENERGY</span><span>{Math.round(state.player.boost)}%</span></div><div className="meter"><i style={{ width: `${state.player.boost}%` }} /></div></div></div>{combat ? <p className={`combat-readout ${combat.kind}`} role="status">{combat.kind === 'damage' ? 'HEAD HIT · −1 INTEGRITY' : 'SHIELD ABSORBED THE HIT'}</p> : null}{activeBuffs.length ? <div className="active-buffs" aria-label="Active automatic bonuses">{activeBuffs.map(kind => <div key={kind} style={{ '--pickup-color': PICKUPS[kind].color } as React.CSSProperties}><span className="buff-symbol">{PICKUPS[kind].symbol}</span><span><strong>{PICKUPS[kind].name}</strong><small>{buffEffects[kind]}</small></span><b>{Math.ceil(state.buffs[kind])}s</b></div>)}</div> : null}</section>
    <section className="hud-tactics panel"><span className="hud-label">TACTICAL SYSTEMS <span>{device === 'keyboard' ? 'E' : 'Y'} TO SWITCH</span></span><div className="tactic-slots">{[{ icon: Radio, title: 'EMP PULSE' }, { icon: Copy, title: 'DECOY' }].map(({ icon: Icon, title }, i) => <div key={title} className={`tactic ${state.selectedSlot === i ? 'selected' : ''} ${state.slots[i] ? 'ready' : ''}`}><Icon size={23} /><div><span>{title}</span><small>{state.slots[i] ? '1 CHARGE' : i === 1 && state.mode === 'campaign' ? 'PRACTICE ONLY' : 'EMPTY'}</small></div>{state.selectedSlot === i ? <kbd>{device === 'keyboard' ? 'SPACE' : 'X'}</kbd> : null}</div>)}</div><p className="tactical-hint">{tacticalHint}</p></section>
    <div className="input-hints">{device === 'keyboard' ? <Keyboard size={16} /> : <Gamepad2 size={17} />}<span>Steer <b>{device === 'keyboard' ? 'WASD / ARROWS' : 'LEFT STICK / D-PAD'}</b></span><span>Boost <b>{device === 'keyboard' ? 'SHIFT' : 'RT'}</b></span><span>Use <b>{use}</b></span><span>Pause <b>{device === 'keyboard' ? 'ESC' : 'MENU'}</b></span></div>

  </div>;
}
