import { Shield, Heart, Zap, Radio, Copy, Pause, Keyboard, Gamepad2 } from 'lucide-react';
import type { Simulation } from '../game/simulation';
import { PICKUPS, CONTENT_VERSION, LEGACY_CONTENT_VERSION } from '../game/content';
import './hud-feedback.css';

type State = Simulation['state'];
export function Hud({ state, device, onPause, best, practice }: { state: State; device: 'keyboard' | 'gamepad'; onPause: () => void; best: number; practice: boolean }) {
  const boss = ['boss', 'boss-intro'].includes(state.status) ? state.boss : null;
  const legacy = state.contentVersion === LEGACY_CONTENT_VERSION;
  const combatUpdate = state.contentVersion === CONTENT_VERSION;
  const bossLaser = combatUpdate && !!boss;
  const fire = device === 'gamepad' ? 'A' : 'F';
  const labPower = state.lab && state.lab !== 'warden' ? state.lab : null;
  const labInstructions = { overdrive: `Hold ${device === 'gamepad' ? 'RT' : 'Shift'} · watch slower boost drain`, surge: 'Collect cyan cores · double their points', magnet: 'Steer near cyan cores · watch them attract', shield: 'Let the hostile shot hit your head', emp: `${device === 'gamepad' ? 'X' : 'Space'} near the drone · watch it disable`, repair: 'Health restored · pause to reset', decoy: `${device === 'gamepad' ? 'X' : 'Space'} before the drone locks`, splice: 'Tail shortened · pause to reset', blaster: `Hold ${fire} · land two hits on the drone`, capacitor: 'Boost refilled by 35 · pause to reset', scrubber: 'Approach a bullet · clears bullets once', 'chain-buffer': 'Watch your combo timer gain three seconds' };
  const use = device === 'keyboard' ? 'SPACE' : 'X';
  const combat = [...state.events].reverse().find(event => ['damage', 'shield-hit'].includes(event.kind) && state.time - event.time < 2);
  const buffEffects = { overdrive: 'Half boost drain', shield: 'Absorbs one attack', surge: 'Core / rival points ×2', magnet: 'Nearby core attraction', scrubber: 'Auto bullet purge armed', 'chain-buffer': 'One combo extension armed' };
  const activeBuffs = (Object.keys(state.buffs) as (keyof typeof state.buffs)[]).filter(kind => state.buffs[kind] > 0);
  const activeDecoy = state.selectedSlot === 1 ? Math.max(0, ...state.decoys.map(decoy => decoy.ttl)) : 0;
  const tacticalHint = activeDecoy > 0 ? `Decoy active · ${Math.ceil(activeDecoy)}s · luring nearby enemies` : state.slots[state.selectedSlot] ? state.selectedSlot === 0 ? `${use} · Disable nearby drones for 3s` : `${use} · Deploy a 4s enemy lure`
    : labPower ? 'Pause to refill or change power.' : state.boss ? 'Tactics optional · charge the laser.'
      : state.selectedSlot === 0 ? state.wave === 1 ? 'EMP pickups start in Wave 2.' : 'Collect ◎ to load EMP.'
        : legacy && state.mode === 'campaign' ? 'Decoy is Practice-only in this run.' : state.wave < 2 || state.wave === 2 && state.coresCollected < 6 ? 'Decoy: Wave 2, after six cores.' : 'Collect ⋈ to load Decoy.';
  const objective = labPower ? state.pickups.some(pickup => pickup.kind === labPower) ? `Collect the marked ${PICKUPS[labPower].name}` : labInstructions[labPower] : state.status === 'extraction' ? 'Warden defeated · exit at top-center' : boss ? bossLaser ? boss.charge >= 3 ? `Hold ${fire} · shoot the glowing ⊕ target` : `Collect sphere ${Math.min(3, boss.charge + 1)} · 1 → 2 → 3` : boss.charge >= 3 ? boss.phase === 'recovery' ? 'Cross green pad · bottom-center' : 'Wait for bottom-center pad to turn green' : `Collect relay ${Math.min(3, boss.charge + 1)} · in order 1 → 2 → 3` : state.wave === 3 ? `Collect ${state.quota} cores · Warden next` : `Collect ${state.quota} energy cores`;
  return <div className="hud" aria-label="Gameplay status">
    <section className="hud-objective panel"><div className="hud-kicker"><span>{state.lab ? 'POWERUP LAB' : practice ? 'PRACTICE' : legacy ? 'LEGACY DISTRICT 01' : !combatUpdate ? 'CLASSIC · ONE LIFE' : 'DISTRICT 01'}</span><span>{labPower ? 'SYSTEM TEST' : state.status === 'extraction' ? 'EXIT OPEN' : boss ? 'WARDEN FINALE' : `WAVE ${state.wave} / 3`}</span></div><h2>{labPower ? PICKUPS[labPower].name.toUpperCase() : boss ? 'THE WARDEN' : state.wave === 3 && state.status !== 'extraction' ? 'HUNTER ENCOUNTER' : 'NEON SPIRE'}</h2><div className="objective-line"><span>{objective}</span>{!boss && !labPower && state.status !== 'extraction' ? <strong>{state.coresCollected} / {state.quota}</strong> : null}</div>{boss ? <div className="boss-counters"><span><span>RELAY CHARGE</span> <b>{boss.charge} / 3</b></span><span><span>ARMOR NODES LEFT</span> <b>{boss.nodes} / 3</b></span></div> : labPower ? <p className="encounter-hint">Practice only · pause to refill or reset.</p> : state.status !== 'extraction' ? <><div className="meter"><i style={{ width: `${state.coresCollected / state.quota * 100}%` }} /></div></> : null}{boss ? <div className={`boss-phase ${boss.phase}`}>{bossLaser ? boss.volley ? 'INCOMING SHOTS · MOVE' : boss.phase === 'attack' ? 'WARDEN FIRING · DODGE' : boss.phase === 'recovery' ? 'WARDEN RELOADING' : 'NEXT WARDEN ATTACK' : boss.phase === 'recovery' ? boss.charge >= 3 ? 'ARMOR OPEN · PAD READY' : 'RECOVERY · CHARGE RELAYS' : boss.phase === 'warning' ? 'LASER FAN · WARNING' : boss.phase === 'attack' ? 'LASER FAN · ACTIVE' : boss.charge >= 3 ? 'CHARGE BANKED · WAIT' : 'COLLECT RELAYS'}<span>{Math.ceil(boss.phaseTime)}s</span></div> : null}</section>
    <section className="hud-score panel"><div><span className="hud-label">{state.lab ? 'LAB SCORE' : 'SCORE'}</span><strong>{state.score.toLocaleString('en-US')}</strong></div><div className="local-best"><span className="hud-label">LOCAL BEST</span><span>{best.toLocaleString('en-US')}</span></div>{state.combo > 1 ? <div className="combo"><span className="hud-label">COMBO</span><strong>×{state.combo}</strong><div className="meter"><i style={{ width: `${state.comboTimer / 5 * 100}%` }} /></div></div> : null}<button className="icon-button" onClick={onPause} aria-label="Pause game"><Pause size={19} /></button></section>
    <section className={`hud-resources panel ${combat?.kind === 'damage' ? 'recent-damage' : ''}`}><div className="resource-line"><Shield size={19} /><div><span className={`hud-label ${combat ? `combat-readout ${combat.kind}` : ''}`} role={combat ? 'status' : undefined}>{combat ? combat.kind === 'damage' ? 'HEAD HIT · −1 HEALTH' : 'SHIELD BLOCKED HIT' : 'HEALTH'}</span><div className="integrity" aria-label={`${state.player.integrity} of ${state.player.maxIntegrity} integrity`}>{Array.from({ length: state.player.maxIntegrity }, (_, i) => <i key={i} className={i < state.player.integrity ? 'filled' : ''} />)}</div></div><span className="length-label">{state.player.length}<small>SEGMENTS</small></span></div><div className="resource-line"><Zap size={20} /><div><div className="boost-label"><span className="hud-label">BOOST ENERGY</span><span>{Math.round(state.player.boost)}%</span></div><div className="meter"><i style={{ width: `${state.player.boost}%` }} /></div></div></div>{combatUpdate && !state.lab ? <div className="lives-display" aria-label={`${state.lives} lives remaining`}><span>LIVES</span><span>{[1, 2, 3].map(life => <Heart key={life} size={16} className={life <= state.lives ? 'remaining' : 'lost'} fill={life <= state.lives ? 'currentColor' : 'none'} />)}</span><b>{state.lives} / 3</b></div> : null}</section>
    <section className="hud-tactics panel"><span className="hud-label">TACTICAL SYSTEMS <span>{device === 'keyboard' ? 'E' : 'Y'} TO SWITCH</span></span><div className="tactic-slots">{[{ icon: Radio, title: 'EMP PULSE', color: '#20dfff' }, { icon: Copy, title: 'DECOY', color: '#cc75ff' }].map(({ icon: Icon, title, color }, i) => <div key={title} style={{ '--tactic-color': color } as React.CSSProperties} aria-label={`${title}: ${state.slots[i] ? 'ready, one charge' : 'empty'}`} className={`tactic ${state.selectedSlot === i ? 'selected' : ''} ${state.slots[i] ? 'ready' : ''}`}><Icon size={23} /><div><span>{title}</span><small>{state.slots[i] ? 'READY ×1' : i === 1 && legacy && state.mode === 'campaign' ? 'PRACTICE ONLY' : 'EMPTY'}</small></div>{state.selectedSlot === i ? <kbd>{device === 'keyboard' ? 'SPACE' : 'X'}</kbd> : null}</div>)}</div><p className="tactical-hint">{tacticalHint}</p>{!legacy ? <div className={`weapon-readout ${bossLaser || state.weapon.ammo > 0 ? 'loaded' : ''}`} aria-label={bossLaser ? 'Boss laser status' : 'Blaster ammunition'}><span>⊕ {bossLaser ? 'SNAKE LASER' : 'PULSE BLASTER'} <small>{bossLaser ? boss.charge === 3 ? `HOLD ${fire} · AIM AT GLOWING TARGET` : 'COLLECT 1 → 2 → 3 TO CHARGE' : state.weapon.ammo ? `HOLD ${fire} · FORWARD AIM ASSIST` : state.status === 'extraction' ? 'EXIT OPEN · STEER TO TOP-CENTER' : state.boss && !combatUpdate ? 'PAD ROUTE ALWAYS AVAILABLE' : 'COLLECT ⊕ · WAVE 2 / 8 CORES'}</small></span><b>{bossLaser ? boss.charge === 3 ? 'READY' : `${boss.charge}/3` : state.weapon.ammo}{!bossLaser ? <small>/ 12</small> : null}</b></div> : null}{boss?.stage === 'exposed' && !legacy ? <p className="receptor-progress">Glowing ⊕ target · {boss.receptorHits} / 3 {bossLaser ? 'laser' : 'blaster'} hits</p> : null}</section>
    {activeBuffs.length ? <div className="active-buffs" aria-label="Active automatic bonuses">{activeBuffs.map(kind => <div key={kind} title={`${PICKUPS[kind].name}: ${buffEffects[kind]}`} aria-label={`${PICKUPS[kind].name}: ${buffEffects[kind]}, ${Math.ceil(state.buffs[kind])} seconds remaining`} style={{ '--pickup-color': PICKUPS[kind].color } as React.CSSProperties}><span className="buff-symbol">{PICKUPS[kind].symbol}</span><span><strong>{PICKUPS[kind].name}</strong><small>{buffEffects[kind]}</small></span><b>{Math.ceil(state.buffs[kind])}s</b></div>)}</div> : null}
    <div className="input-hints">{device === 'keyboard' ? <Keyboard size={16} /> : <Gamepad2 size={17} />}<span>Steer <b>{device === 'keyboard' ? 'WASD / ARROWS' : 'LEFT STICK / D-PAD'}</b></span><span>Boost <b>{device === 'keyboard' ? 'SHIFT' : 'RT'}</b></span><span>Use <b>{use}</b></span>{!legacy ? <span>Fire <b>{fire}</b></span> : null}<span>Pause <b>{device === 'keyboard' ? 'ESC' : 'MENU'}</b></span></div>

  </div>;
}
